# log configuration
log:
  # root path
  path: ./logs
  # level
  level: debug
  # log to console
  console: true

# service configuration
serv:
  # bindaddr - bind addr
  bindaddr: 0.0.0.0:7205

tokens:
  - uiPobCUJ0kXwonOm

# configuration for jccclient
jccclient: ./config/jccclient.yaml

# path for template
tmplpath: ./cfg/tmpl

# plugins
plugins:
  - alimama
  - techinasia
  - steepandcheap
  - mountainsteals

# configuration for plugins
pluginscfg:
  alimama: ./cfg/alimama.yaml
  steepandcheap: ./cfg/steepandcheap.yaml

# configuration for Ada
ada:
  servaddr: 127.0.0.1:7201
  token: 123456

# path for task logs
tasklogspath: ./tasklogs
# Does it call initJieba
isinitjieba: true
# Does it call initOpenCC
openccpath: ./cfg/opencc
# api serv bind address
apiserv: :7206