# log configuration
log:
  # root path
  path: ./logs
  # level
  level: debug
  # log to console
  console: true

# service configuration
serv:
  # bindaddr - bind addr
  bindaddr: 0.0.0.0:7205

tokens:
  - uiPobCUJ0kXwonOm

# configuration for jccclient
jccclient: ./config/jccclient.yaml  

# plugins
plugins:
  - alimama
  - techinasia
  - steepandcheap
  - mountainsteals

# configuration for plugins
pluginscfg:
  alimama: ./cfg/alimama.yaml
  steepandcheap: ./cfg/steepandcheap.yaml
